name: graduatioproject
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: ^3.6.0
dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.16
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  shared_preferences: ^2.3.4
  connectivity_plus: ^6.1.1
  carousel_slider_plus: ^7.1.0
  smooth_page_indicator: ^1.2.0+3
  flutter_chat_ui: ^1.6.15
  flutter_chat_types: ^3.6.2
  pin_code_fields: ^8.0.1
  sms_autofill: ^2.4.1
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Poppins
      fonts: 
        - asset: assets/fonts/PoppinsSemiBold.ttf
          weight: 600
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
        - asset: assets/fonts/PoppinsBold.ttf
          weight: 700
        - asset: assets/fonts/PoppinsLight.ttf
          weight: 300
        - asset: assets/fonts/PoppinsExtraBold.ttf
          weight: 800
    - family: Cairo
      fonts: 
        - asset: assets/fonts/CairoSemiBold.ttf
          weight: 600
        - asset: assets/fonts/CairoRegular.ttf
          weight: 400
        - asset: assets/fonts/CairoBold.ttf
          weight: 700
        - asset: assets/fonts/CairoMedium.ttf
          weight: 500
    - family: Tajawal
      fonts: 
        - asset: assets/fonts/TajawalRegular.ttf
          weight: 400
